source: src/
destination: _site/



defaults:
  -
#    scope:
#      path: "" # an empty string here means all files in the project
    values:
#      layout: "default"
      meta-description: "Талантливый backend-разработчик из Санкт-Петербурга родом из Москвы."