#source: .
destination: _site/
baseurl: /WebProgramming

include:
  - node_modules

sass:
  sass_dir: assets/_sass

defaults:
  -
#    scope:
#      path: "" # an empty string here means all files in the project
    values:
#      layout: "default"
      title: "Разработчик Георгий Семенов | Личная страница"
      meta-description: "Талантливый backend-разработчик из Санкт-Петербурга родом из Москвы."
      meta-keywords: "разработка, олимпиада, backend, программирование, преподавание"
      meta-author: "Георгий Семенов"
      page-menu: "UNSET"